# Hush Providers - Resource Configuration
# This file configures LLM, embedding, and reranking resources for the ResourceHub.

# LLM Configurations
llm:claude-4-sonnet:
  _class: OpenAIConfig
  api_key: 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
  api_type: openai
  base_url: https://openrouter.ai/api/v1
  model: anthropic/claude-sonnet-4

# Embedding Configurations
embedding:bge-m3:
  _class: EmbeddingConfig
  api_key: jROPAGbbRqVMikqLdSqM4WYcLg3u17LN
  api_type: vllm
  base_url: https://api.deepinfra.com/v1/openai/embeddings
  dimensions: 1024
  model: BAAI/bge-m3

embedding:bge-m3-onnx:
  _class: EmbeddingConfig
  api_type: onnx
  model: /home/thanglq150188/Work/bge-m3
  dimensions: 1024

# Reranking Configurations
reranking:bge-m3:
  _class: RerankingConfig
  api_key: pcsk_PUQQE_P3wTFf7va2dxiWs5sHsvvkfu8qU2GJhTNRkiTnYxzmT2F4KwGpe1BPLFejBfTdi
  api_type: pinecone
  api_version: 2025-04
  base_url: https://api.pinecone.io/rerank
  model: bge-reranker-v2-m3
